### ISSUE TITLE
v run . examples go NOT work

### ISSUE THREAD

**Issue by vajrabisj** [holder66/vhammll#3]
as captioned issue...

system responding no such command...

**Comment by holder66** [comment]
@vajrabisj Could you kindly post what you put on the command line, and what the system responded ? Thank you!

**Comment by vajrabisj** [comment]
after entering ./main examples
the response is:
Description:
"examples" displays information about running the various commands, shows
a typical command interface line illustrating the example, prompts the user
to continue by hitting the "return" key, and then executes the example 
and displays the result on the console. 

Usage:
To start the demonstration, enter "v run . examples go"

Options:
To stop before completing the demo, hit ctrl-C

processing time: 0 hrs 0 min  0.000 sec


after entering ./main examples go
response is:
unrecognized command
processing time: 0 hrs 0 min  0.000 sec

**Comment by vajrabisj** [comment]
other commands, such as ./main explore blabla are running normal...

**Comment by vajrabisj** [comment]
basicly i now know how to use your package, it's GREAT!

for those string attributes, such as eg play-tennis dataset, how to proceed? thx!

**Comment by holder66** [comment]
Are you referring to the PlayTennis.csv dataset (https://gist.github.com/DiogoRibeiro7/c6590d0cf119e87c39e31c21a9c0f3a8)?

The easiest way to use a csv dataset is to convert it to a tab-delimited file. You can do that in a spreadsheet app, or with somewhat more difficulty in a text editor. Specify the “class” attribute by prefixing its name with c#.

re the examples command: should be working now, although there may still be some problems inside the examples.v file.

**Comment by vajrabisj** [comment]
really appreciate your swift replies!

your works are GREAT!

**Comment by holder66** [comment]
Thanks, @vajrabisj!
I invite you to add a star to the vhammll repo.
Also, I added code to load csv datasets (like those used in Kaggle) directly, ie no need to convert to tab-delimited format.

Henry

**Comment by vajrabisj** [comment]
Yes, done. Thx!

Henry Olders ***@***.***>于2023年10月1日 周日23:16写道：

> Thanks, @vajrabisj!
> I invite you to add a star to the vhammll repo.
> Also, I added code to load csv datasets (like those used in Kaggle)
> directly, ie no need to convert to tab-delimited format.
>
> Henry
>
